/*******************************************************************************
 * Copyright 2018 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_datamodel_aml_AMLObject */

#ifndef _Included_org_datamodel_aml_AMLObject
#define _Included_org_datamodel_aml_AMLObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    constructAMLObject
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_datamodel_aml_AMLObject_constructAMLObject__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    constructAMLObject
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_datamodel_aml_AMLObject_constructAMLObject__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    addDataImpl
 * Signature: (Ljava/lang/String;Lorg/datamodel/aml/AMLData;)V
 */
JNIEXPORT void JNICALL Java_org_datamodel_aml_AMLObject_addDataImpl
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    getDataImpl
 * Signature: (Ljava/lang/String;)Lorg/datamodel/aml/AMLData;
 */
JNIEXPORT jobject JNICALL Java_org_datamodel_aml_AMLObject_getDataImpl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    getDataNamesImpl
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_datamodel_aml_AMLObject_getDataNamesImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    getDeviceIdImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_datamodel_aml_AMLObject_getDeviceIdImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    getTimeStampImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_datamodel_aml_AMLObject_getTimeStampImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    getIdImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_datamodel_aml_AMLObject_getIdImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_datamodel_aml_AMLObject
 * Method:    destructAMLObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_datamodel_aml_AMLObject_destructAMLObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
