/*******************************************************************************
 * Copyright 2018 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_datamodel_aml_Representation */

#ifndef _Included_org_datamodel_aml_Representation
#define _Included_org_datamodel_aml_Representation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_datamodel_aml_Representation
 * Method:    constructRepresentation
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_datamodel_aml_Representation_constructRepresentation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_datamodel_aml_Representation
 * Method:    DataToAmlImpl
 * Signature: (Lorg/datamodel/aml/AMLObject;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_datamodel_aml_Representation_DataToAmlImpl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_datamodel_aml_Representation
 * Method:    AmlToDataImpl
 * Signature: (Ljava/lang/String;)Lorg/datamodel/aml/AMLObject;
 */
JNIEXPORT jobject JNICALL Java_org_datamodel_aml_Representation_AmlToDataImpl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_datamodel_aml_Representation
 * Method:    DataToByteImpl
 * Signature: (Lorg/datamodel/aml/AMLObject;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_datamodel_aml_Representation_DataToByteImpl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_datamodel_aml_Representation
 * Method:    ByteToDataImpl
 * Signature: ([B)Lorg/datamodel/aml/AMLObject;
 */
JNIEXPORT jobject JNICALL Java_org_datamodel_aml_Representation_ByteToDataImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_datamodel_aml_Representation
 * Method:    getRepresentationIdImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_datamodel_aml_Representation_getRepresentationIdImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_datamodel_aml_Representation
 * Method:    getConfigInfoImpl
 * Signature: ()Lorg/datamodel/aml/AMLObject;
 */
JNIEXPORT jobject JNICALL Java_org_datamodel_aml_Representation_getConfigInfoImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
