// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package edge.datamodel.protobuf.event;

public final class ProtoEvent {
  private ProtoEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:datamodel.Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required int64 created = 2;</code>
     */
    boolean hasCreated();
    /**
     * <code>required int64 created = 2;</code>
     */
    long getCreated();

    /**
     * <code>required int64 modified = 3;</code>
     */
    boolean hasModified();
    /**
     * <code>required int64 modified = 3;</code>
     */
    long getModified();

    /**
     * <code>required int64 origin = 4;</code>
     */
    boolean hasOrigin();
    /**
     * <code>required int64 origin = 4;</code>
     */
    long getOrigin();

    /**
     * <code>required int64 pushed = 5;</code>
     */
    boolean hasPushed();
    /**
     * <code>required int64 pushed = 5;</code>
     */
    long getPushed();

    /**
     * <code>required string device = 6;</code>
     */
    boolean hasDevice();
    /**
     * <code>required string device = 6;</code>
     */
    java.lang.String getDevice();
    /**
     * <code>required string device = 6;</code>
     */
    com.google.protobuf.ByteString
        getDeviceBytes();

    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    java.util.List<edge.datamodel.protobuf.event.ProtoEvent.Reading> 
        getReadingList();
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    edge.datamodel.protobuf.event.ProtoEvent.Reading getReading(int index);
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    int getReadingCount();
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    java.util.List<? extends edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder> 
        getReadingOrBuilderList();
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder getReadingOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code datamodel.Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:datamodel.Event)
      EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
      id_ = "";
      created_ = 0L;
      modified_ = 0L;
      origin_ = 0L;
      pushed_ = 0L;
      device_ = "";
      reading_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              created_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              modified_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              origin_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              pushed_ = input.readInt64();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              device_ = bs;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                reading_ = new java.util.ArrayList<edge.datamodel.protobuf.event.ProtoEvent.Reading>();
                mutable_bitField0_ |= 0x00000040;
              }
              reading_.add(
                  input.readMessage(edge.datamodel.protobuf.event.ProtoEvent.Reading.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          reading_ = java.util.Collections.unmodifiableList(reading_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edge.datamodel.protobuf.event.ProtoEvent.Event.class, edge.datamodel.protobuf.event.ProtoEvent.Event.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_FIELD_NUMBER = 2;
    private long created_;
    /**
     * <code>required int64 created = 2;</code>
     */
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 created = 2;</code>
     */
    public long getCreated() {
      return created_;
    }

    public static final int MODIFIED_FIELD_NUMBER = 3;
    private long modified_;
    /**
     * <code>required int64 modified = 3;</code>
     */
    public boolean hasModified() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 modified = 3;</code>
     */
    public long getModified() {
      return modified_;
    }

    public static final int ORIGIN_FIELD_NUMBER = 4;
    private long origin_;
    /**
     * <code>required int64 origin = 4;</code>
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 origin = 4;</code>
     */
    public long getOrigin() {
      return origin_;
    }

    public static final int PUSHED_FIELD_NUMBER = 5;
    private long pushed_;
    /**
     * <code>required int64 pushed = 5;</code>
     */
    public boolean hasPushed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 pushed = 5;</code>
     */
    public long getPushed() {
      return pushed_;
    }

    public static final int DEVICE_FIELD_NUMBER = 6;
    private volatile java.lang.Object device_;
    /**
     * <code>required string device = 6;</code>
     */
    public boolean hasDevice() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string device = 6;</code>
     */
    public java.lang.String getDevice() {
      java.lang.Object ref = device_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          device_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceBytes() {
      java.lang.Object ref = device_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        device_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int READING_FIELD_NUMBER = 7;
    private java.util.List<edge.datamodel.protobuf.event.ProtoEvent.Reading> reading_;
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    public java.util.List<edge.datamodel.protobuf.event.ProtoEvent.Reading> getReadingList() {
      return reading_;
    }
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    public java.util.List<? extends edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder> 
        getReadingOrBuilderList() {
      return reading_;
    }
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    public int getReadingCount() {
      return reading_.size();
    }
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    public edge.datamodel.protobuf.event.ProtoEvent.Reading getReading(int index) {
      return reading_.get(index);
    }
    /**
     * <code>repeated .datamodel.Reading reading = 7;</code>
     */
    public edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder getReadingOrBuilder(
        int index) {
      return reading_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModified()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrigin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPushed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDevice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getReadingCount(); i++) {
        if (!getReading(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, created_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, modified_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, origin_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, pushed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, device_);
      }
      for (int i = 0; i < reading_.size(); i++) {
        output.writeMessage(7, reading_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, created_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, modified_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, origin_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, pushed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, device_);
      }
      for (int i = 0; i < reading_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, reading_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edge.datamodel.protobuf.event.ProtoEvent.Event)) {
        return super.equals(obj);
      }
      edge.datamodel.protobuf.event.ProtoEvent.Event other = (edge.datamodel.protobuf.event.ProtoEvent.Event) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasCreated() == other.hasCreated());
      if (hasCreated()) {
        result = result && (getCreated()
            == other.getCreated());
      }
      result = result && (hasModified() == other.hasModified());
      if (hasModified()) {
        result = result && (getModified()
            == other.getModified());
      }
      result = result && (hasOrigin() == other.hasOrigin());
      if (hasOrigin()) {
        result = result && (getOrigin()
            == other.getOrigin());
      }
      result = result && (hasPushed() == other.hasPushed());
      if (hasPushed()) {
        result = result && (getPushed()
            == other.getPushed());
      }
      result = result && (hasDevice() == other.hasDevice());
      if (hasDevice()) {
        result = result && getDevice()
            .equals(other.getDevice());
      }
      result = result && getReadingList()
          .equals(other.getReadingList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasCreated()) {
        hash = (37 * hash) + CREATED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreated());
      }
      if (hasModified()) {
        hash = (37 * hash) + MODIFIED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getModified());
      }
      if (hasOrigin()) {
        hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOrigin());
      }
      if (hasPushed()) {
        hash = (37 * hash) + PUSHED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPushed());
      }
      if (hasDevice()) {
        hash = (37 * hash) + DEVICE_FIELD_NUMBER;
        hash = (53 * hash) + getDevice().hashCode();
      }
      if (getReadingCount() > 0) {
        hash = (37 * hash) + READING_FIELD_NUMBER;
        hash = (53 * hash) + getReadingList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edge.datamodel.protobuf.event.ProtoEvent.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code datamodel.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:datamodel.Event)
        edge.datamodel.protobuf.event.ProtoEvent.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edge.datamodel.protobuf.event.ProtoEvent.Event.class, edge.datamodel.protobuf.event.ProtoEvent.Event.Builder.class);
      }

      // Construct using edge.datamodel.protobuf.event.ProtoEvent.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReadingFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        created_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        modified_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        origin_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        pushed_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        device_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (readingBuilder_ == null) {
          reading_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          readingBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Event_descriptor;
      }

      public edge.datamodel.protobuf.event.ProtoEvent.Event getDefaultInstanceForType() {
        return edge.datamodel.protobuf.event.ProtoEvent.Event.getDefaultInstance();
      }

      public edge.datamodel.protobuf.event.ProtoEvent.Event build() {
        edge.datamodel.protobuf.event.ProtoEvent.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edge.datamodel.protobuf.event.ProtoEvent.Event buildPartial() {
        edge.datamodel.protobuf.event.ProtoEvent.Event result = new edge.datamodel.protobuf.event.ProtoEvent.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.created_ = created_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.modified_ = modified_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.origin_ = origin_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pushed_ = pushed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.device_ = device_;
        if (readingBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            reading_ = java.util.Collections.unmodifiableList(reading_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.reading_ = reading_;
        } else {
          result.reading_ = readingBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edge.datamodel.protobuf.event.ProtoEvent.Event) {
          return mergeFrom((edge.datamodel.protobuf.event.ProtoEvent.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edge.datamodel.protobuf.event.ProtoEvent.Event other) {
        if (other == edge.datamodel.protobuf.event.ProtoEvent.Event.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCreated()) {
          setCreated(other.getCreated());
        }
        if (other.hasModified()) {
          setModified(other.getModified());
        }
        if (other.hasOrigin()) {
          setOrigin(other.getOrigin());
        }
        if (other.hasPushed()) {
          setPushed(other.getPushed());
        }
        if (other.hasDevice()) {
          bitField0_ |= 0x00000020;
          device_ = other.device_;
          onChanged();
        }
        if (readingBuilder_ == null) {
          if (!other.reading_.isEmpty()) {
            if (reading_.isEmpty()) {
              reading_ = other.reading_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureReadingIsMutable();
              reading_.addAll(other.reading_);
            }
            onChanged();
          }
        } else {
          if (!other.reading_.isEmpty()) {
            if (readingBuilder_.isEmpty()) {
              readingBuilder_.dispose();
              readingBuilder_ = null;
              reading_ = other.reading_;
              bitField0_ = (bitField0_ & ~0x00000040);
              readingBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getReadingFieldBuilder() : null;
            } else {
              readingBuilder_.addAllMessages(other.reading_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasCreated()) {
          return false;
        }
        if (!hasModified()) {
          return false;
        }
        if (!hasOrigin()) {
          return false;
        }
        if (!hasPushed()) {
          return false;
        }
        if (!hasDevice()) {
          return false;
        }
        for (int i = 0; i < getReadingCount(); i++) {
          if (!getReading(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edge.datamodel.protobuf.event.ProtoEvent.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edge.datamodel.protobuf.event.ProtoEvent.Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private long created_ ;
      /**
       * <code>required int64 created = 2;</code>
       */
      public boolean hasCreated() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 created = 2;</code>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>required int64 created = 2;</code>
       */
      public Builder setCreated(long value) {
        bitField0_ |= 0x00000002;
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 created = 2;</code>
       */
      public Builder clearCreated() {
        bitField0_ = (bitField0_ & ~0x00000002);
        created_ = 0L;
        onChanged();
        return this;
      }

      private long modified_ ;
      /**
       * <code>required int64 modified = 3;</code>
       */
      public boolean hasModified() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 modified = 3;</code>
       */
      public long getModified() {
        return modified_;
      }
      /**
       * <code>required int64 modified = 3;</code>
       */
      public Builder setModified(long value) {
        bitField0_ |= 0x00000004;
        modified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 modified = 3;</code>
       */
      public Builder clearModified() {
        bitField0_ = (bitField0_ & ~0x00000004);
        modified_ = 0L;
        onChanged();
        return this;
      }

      private long origin_ ;
      /**
       * <code>required int64 origin = 4;</code>
       */
      public boolean hasOrigin() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 origin = 4;</code>
       */
      public long getOrigin() {
        return origin_;
      }
      /**
       * <code>required int64 origin = 4;</code>
       */
      public Builder setOrigin(long value) {
        bitField0_ |= 0x00000008;
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 origin = 4;</code>
       */
      public Builder clearOrigin() {
        bitField0_ = (bitField0_ & ~0x00000008);
        origin_ = 0L;
        onChanged();
        return this;
      }

      private long pushed_ ;
      /**
       * <code>required int64 pushed = 5;</code>
       */
      public boolean hasPushed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 pushed = 5;</code>
       */
      public long getPushed() {
        return pushed_;
      }
      /**
       * <code>required int64 pushed = 5;</code>
       */
      public Builder setPushed(long value) {
        bitField0_ |= 0x00000010;
        pushed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 pushed = 5;</code>
       */
      public Builder clearPushed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pushed_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object device_ = "";
      /**
       * <code>required string device = 6;</code>
       */
      public boolean hasDevice() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string device = 6;</code>
       */
      public java.lang.String getDevice() {
        java.lang.Object ref = device_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            device_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceBytes() {
        java.lang.Object ref = device_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          device_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device = 6;</code>
       */
      public Builder setDevice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        device_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device = 6;</code>
       */
      public Builder clearDevice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        device_ = getDefaultInstance().getDevice();
        onChanged();
        return this;
      }
      /**
       * <code>required string device = 6;</code>
       */
      public Builder setDeviceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        device_ = value;
        onChanged();
        return this;
      }

      private java.util.List<edge.datamodel.protobuf.event.ProtoEvent.Reading> reading_ =
        java.util.Collections.emptyList();
      private void ensureReadingIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          reading_ = new java.util.ArrayList<edge.datamodel.protobuf.event.ProtoEvent.Reading>(reading_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          edge.datamodel.protobuf.event.ProtoEvent.Reading, edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder, edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder> readingBuilder_;

      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public java.util.List<edge.datamodel.protobuf.event.ProtoEvent.Reading> getReadingList() {
        if (readingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reading_);
        } else {
          return readingBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public int getReadingCount() {
        if (readingBuilder_ == null) {
          return reading_.size();
        } else {
          return readingBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public edge.datamodel.protobuf.event.ProtoEvent.Reading getReading(int index) {
        if (readingBuilder_ == null) {
          return reading_.get(index);
        } else {
          return readingBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder setReading(
          int index, edge.datamodel.protobuf.event.ProtoEvent.Reading value) {
        if (readingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadingIsMutable();
          reading_.set(index, value);
          onChanged();
        } else {
          readingBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder setReading(
          int index, edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder builderForValue) {
        if (readingBuilder_ == null) {
          ensureReadingIsMutable();
          reading_.set(index, builderForValue.build());
          onChanged();
        } else {
          readingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder addReading(edge.datamodel.protobuf.event.ProtoEvent.Reading value) {
        if (readingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadingIsMutable();
          reading_.add(value);
          onChanged();
        } else {
          readingBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder addReading(
          int index, edge.datamodel.protobuf.event.ProtoEvent.Reading value) {
        if (readingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadingIsMutable();
          reading_.add(index, value);
          onChanged();
        } else {
          readingBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder addReading(
          edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder builderForValue) {
        if (readingBuilder_ == null) {
          ensureReadingIsMutable();
          reading_.add(builderForValue.build());
          onChanged();
        } else {
          readingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder addReading(
          int index, edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder builderForValue) {
        if (readingBuilder_ == null) {
          ensureReadingIsMutable();
          reading_.add(index, builderForValue.build());
          onChanged();
        } else {
          readingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder addAllReading(
          java.lang.Iterable<? extends edge.datamodel.protobuf.event.ProtoEvent.Reading> values) {
        if (readingBuilder_ == null) {
          ensureReadingIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, reading_);
          onChanged();
        } else {
          readingBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder clearReading() {
        if (readingBuilder_ == null) {
          reading_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          readingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public Builder removeReading(int index) {
        if (readingBuilder_ == null) {
          ensureReadingIsMutable();
          reading_.remove(index);
          onChanged();
        } else {
          readingBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder getReadingBuilder(
          int index) {
        return getReadingFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder getReadingOrBuilder(
          int index) {
        if (readingBuilder_ == null) {
          return reading_.get(index);  } else {
          return readingBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public java.util.List<? extends edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder> 
           getReadingOrBuilderList() {
        if (readingBuilder_ != null) {
          return readingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reading_);
        }
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder addReadingBuilder() {
        return getReadingFieldBuilder().addBuilder(
            edge.datamodel.protobuf.event.ProtoEvent.Reading.getDefaultInstance());
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder addReadingBuilder(
          int index) {
        return getReadingFieldBuilder().addBuilder(
            index, edge.datamodel.protobuf.event.ProtoEvent.Reading.getDefaultInstance());
      }
      /**
       * <code>repeated .datamodel.Reading reading = 7;</code>
       */
      public java.util.List<edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder> 
           getReadingBuilderList() {
        return getReadingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          edge.datamodel.protobuf.event.ProtoEvent.Reading, edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder, edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder> 
          getReadingFieldBuilder() {
        if (readingBuilder_ == null) {
          readingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              edge.datamodel.protobuf.event.ProtoEvent.Reading, edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder, edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder>(
                  reading_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          reading_ = null;
        }
        return readingBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:datamodel.Event)
    }

    // @@protoc_insertion_point(class_scope:datamodel.Event)
    private static final edge.datamodel.protobuf.event.ProtoEvent.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edge.datamodel.protobuf.event.ProtoEvent.Event();
    }

    public static edge.datamodel.protobuf.event.ProtoEvent.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Event(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    public edge.datamodel.protobuf.event.ProtoEvent.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:datamodel.Reading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required int64 created = 2;</code>
     */
    boolean hasCreated();
    /**
     * <code>required int64 created = 2;</code>
     */
    long getCreated();

    /**
     * <code>required int64 modified = 3;</code>
     */
    boolean hasModified();
    /**
     * <code>required int64 modified = 3;</code>
     */
    long getModified();

    /**
     * <code>required int64 origin = 4;</code>
     */
    boolean hasOrigin();
    /**
     * <code>required int64 origin = 4;</code>
     */
    long getOrigin();

    /**
     * <code>required int64 pushed = 5;</code>
     */
    boolean hasPushed();
    /**
     * <code>required int64 pushed = 5;</code>
     */
    long getPushed();

    /**
     * <code>required string name = 6;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 6;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 6;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string value = 7;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 7;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 7;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>required string device = 8;</code>
     */
    boolean hasDevice();
    /**
     * <code>required string device = 8;</code>
     */
    java.lang.String getDevice();
    /**
     * <code>required string device = 8;</code>
     */
    com.google.protobuf.ByteString
        getDeviceBytes();
  }
  /**
   * Protobuf type {@code datamodel.Reading}
   */
  public  static final class Reading extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:datamodel.Reading)
      ReadingOrBuilder {
    // Use Reading.newBuilder() to construct.
    private Reading(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reading() {
      id_ = "";
      created_ = 0L;
      modified_ = 0L;
      origin_ = 0L;
      pushed_ = 0L;
      name_ = "";
      value_ = "";
      device_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Reading(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              created_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              modified_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              origin_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              pushed_ = input.readInt64();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              name_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              value_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              device_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Reading_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Reading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edge.datamodel.protobuf.event.ProtoEvent.Reading.class, edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_FIELD_NUMBER = 2;
    private long created_;
    /**
     * <code>required int64 created = 2;</code>
     */
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 created = 2;</code>
     */
    public long getCreated() {
      return created_;
    }

    public static final int MODIFIED_FIELD_NUMBER = 3;
    private long modified_;
    /**
     * <code>required int64 modified = 3;</code>
     */
    public boolean hasModified() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 modified = 3;</code>
     */
    public long getModified() {
      return modified_;
    }

    public static final int ORIGIN_FIELD_NUMBER = 4;
    private long origin_;
    /**
     * <code>required int64 origin = 4;</code>
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 origin = 4;</code>
     */
    public long getOrigin() {
      return origin_;
    }

    public static final int PUSHED_FIELD_NUMBER = 5;
    private long pushed_;
    /**
     * <code>required int64 pushed = 5;</code>
     */
    public boolean hasPushed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 pushed = 5;</code>
     */
    public long getPushed() {
      return pushed_;
    }

    public static final int NAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 6;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string name = 6;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 7;
    private volatile java.lang.Object value_;
    /**
     * <code>required string value = 7;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string value = 7;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 7;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_FIELD_NUMBER = 8;
    private volatile java.lang.Object device_;
    /**
     * <code>required string device = 8;</code>
     */
    public boolean hasDevice() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string device = 8;</code>
     */
    public java.lang.String getDevice() {
      java.lang.Object ref = device_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          device_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceBytes() {
      java.lang.Object ref = device_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        device_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModified()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrigin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPushed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDevice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, created_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, modified_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, origin_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, pushed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, value_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, device_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, created_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, modified_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, origin_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, pushed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, value_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, device_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edge.datamodel.protobuf.event.ProtoEvent.Reading)) {
        return super.equals(obj);
      }
      edge.datamodel.protobuf.event.ProtoEvent.Reading other = (edge.datamodel.protobuf.event.ProtoEvent.Reading) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasCreated() == other.hasCreated());
      if (hasCreated()) {
        result = result && (getCreated()
            == other.getCreated());
      }
      result = result && (hasModified() == other.hasModified());
      if (hasModified()) {
        result = result && (getModified()
            == other.getModified());
      }
      result = result && (hasOrigin() == other.hasOrigin());
      if (hasOrigin()) {
        result = result && (getOrigin()
            == other.getOrigin());
      }
      result = result && (hasPushed() == other.hasPushed());
      if (hasPushed()) {
        result = result && (getPushed()
            == other.getPushed());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && (hasDevice() == other.hasDevice());
      if (hasDevice()) {
        result = result && getDevice()
            .equals(other.getDevice());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasCreated()) {
        hash = (37 * hash) + CREATED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreated());
      }
      if (hasModified()) {
        hash = (37 * hash) + MODIFIED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getModified());
      }
      if (hasOrigin()) {
        hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOrigin());
      }
      if (hasPushed()) {
        hash = (37 * hash) + PUSHED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPushed());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasDevice()) {
        hash = (37 * hash) + DEVICE_FIELD_NUMBER;
        hash = (53 * hash) + getDevice().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edge.datamodel.protobuf.event.ProtoEvent.Reading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edge.datamodel.protobuf.event.ProtoEvent.Reading prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code datamodel.Reading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:datamodel.Reading)
        edge.datamodel.protobuf.event.ProtoEvent.ReadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Reading_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Reading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edge.datamodel.protobuf.event.ProtoEvent.Reading.class, edge.datamodel.protobuf.event.ProtoEvent.Reading.Builder.class);
      }

      // Construct using edge.datamodel.protobuf.event.ProtoEvent.Reading.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        created_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        modified_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        origin_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        pushed_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        device_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edge.datamodel.protobuf.event.ProtoEvent.internal_static_datamodel_Reading_descriptor;
      }

      public edge.datamodel.protobuf.event.ProtoEvent.Reading getDefaultInstanceForType() {
        return edge.datamodel.protobuf.event.ProtoEvent.Reading.getDefaultInstance();
      }

      public edge.datamodel.protobuf.event.ProtoEvent.Reading build() {
        edge.datamodel.protobuf.event.ProtoEvent.Reading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edge.datamodel.protobuf.event.ProtoEvent.Reading buildPartial() {
        edge.datamodel.protobuf.event.ProtoEvent.Reading result = new edge.datamodel.protobuf.event.ProtoEvent.Reading(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.created_ = created_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.modified_ = modified_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.origin_ = origin_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pushed_ = pushed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.device_ = device_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edge.datamodel.protobuf.event.ProtoEvent.Reading) {
          return mergeFrom((edge.datamodel.protobuf.event.ProtoEvent.Reading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edge.datamodel.protobuf.event.ProtoEvent.Reading other) {
        if (other == edge.datamodel.protobuf.event.ProtoEvent.Reading.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCreated()) {
          setCreated(other.getCreated());
        }
        if (other.hasModified()) {
          setModified(other.getModified());
        }
        if (other.hasOrigin()) {
          setOrigin(other.getOrigin());
        }
        if (other.hasPushed()) {
          setPushed(other.getPushed());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000020;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000040;
          value_ = other.value_;
          onChanged();
        }
        if (other.hasDevice()) {
          bitField0_ |= 0x00000080;
          device_ = other.device_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasCreated()) {
          return false;
        }
        if (!hasModified()) {
          return false;
        }
        if (!hasOrigin()) {
          return false;
        }
        if (!hasPushed()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        if (!hasDevice()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edge.datamodel.protobuf.event.ProtoEvent.Reading parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edge.datamodel.protobuf.event.ProtoEvent.Reading) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private long created_ ;
      /**
       * <code>required int64 created = 2;</code>
       */
      public boolean hasCreated() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 created = 2;</code>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>required int64 created = 2;</code>
       */
      public Builder setCreated(long value) {
        bitField0_ |= 0x00000002;
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 created = 2;</code>
       */
      public Builder clearCreated() {
        bitField0_ = (bitField0_ & ~0x00000002);
        created_ = 0L;
        onChanged();
        return this;
      }

      private long modified_ ;
      /**
       * <code>required int64 modified = 3;</code>
       */
      public boolean hasModified() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 modified = 3;</code>
       */
      public long getModified() {
        return modified_;
      }
      /**
       * <code>required int64 modified = 3;</code>
       */
      public Builder setModified(long value) {
        bitField0_ |= 0x00000004;
        modified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 modified = 3;</code>
       */
      public Builder clearModified() {
        bitField0_ = (bitField0_ & ~0x00000004);
        modified_ = 0L;
        onChanged();
        return this;
      }

      private long origin_ ;
      /**
       * <code>required int64 origin = 4;</code>
       */
      public boolean hasOrigin() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 origin = 4;</code>
       */
      public long getOrigin() {
        return origin_;
      }
      /**
       * <code>required int64 origin = 4;</code>
       */
      public Builder setOrigin(long value) {
        bitField0_ |= 0x00000008;
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 origin = 4;</code>
       */
      public Builder clearOrigin() {
        bitField0_ = (bitField0_ & ~0x00000008);
        origin_ = 0L;
        onChanged();
        return this;
      }

      private long pushed_ ;
      /**
       * <code>required int64 pushed = 5;</code>
       */
      public boolean hasPushed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 pushed = 5;</code>
       */
      public long getPushed() {
        return pushed_;
      }
      /**
       * <code>required int64 pushed = 5;</code>
       */
      public Builder setPushed(long value) {
        bitField0_ |= 0x00000010;
        pushed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 pushed = 5;</code>
       */
      public Builder clearPushed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pushed_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 6;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string name = 6;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 6;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 6;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 6;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 7;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string value = 7;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 7;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 7;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 7;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 7;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        value_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object device_ = "";
      /**
       * <code>required string device = 8;</code>
       */
      public boolean hasDevice() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string device = 8;</code>
       */
      public java.lang.String getDevice() {
        java.lang.Object ref = device_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            device_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceBytes() {
        java.lang.Object ref = device_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          device_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device = 8;</code>
       */
      public Builder setDevice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        device_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device = 8;</code>
       */
      public Builder clearDevice() {
        bitField0_ = (bitField0_ & ~0x00000080);
        device_ = getDefaultInstance().getDevice();
        onChanged();
        return this;
      }
      /**
       * <code>required string device = 8;</code>
       */
      public Builder setDeviceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        device_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:datamodel.Reading)
    }

    // @@protoc_insertion_point(class_scope:datamodel.Reading)
    private static final edge.datamodel.protobuf.event.ProtoEvent.Reading DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edge.datamodel.protobuf.event.ProtoEvent.Reading();
    }

    public static edge.datamodel.protobuf.event.ProtoEvent.Reading getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Reading>
        PARSER = new com.google.protobuf.AbstractParser<Reading>() {
      public Reading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Reading(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reading> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reading> getParserForType() {
      return PARSER;
    }

    public edge.datamodel.protobuf.event.ProtoEvent.Reading getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datamodel_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datamodel_Event_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datamodel_Reading_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datamodel_Reading_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022\tdatamodel\"\213\001\n\005Event\022\n\n\002id" +
      "\030\001 \002(\t\022\017\n\007created\030\002 \002(\003\022\020\n\010modified\030\003 \002(" +
      "\003\022\016\n\006origin\030\004 \002(\003\022\016\n\006pushed\030\005 \002(\003\022\016\n\006dev" +
      "ice\030\006 \002(\t\022#\n\007reading\030\007 \003(\0132\022.datamodel.R" +
      "eading\"\205\001\n\007Reading\022\n\n\002id\030\001 \002(\t\022\017\n\007create" +
      "d\030\002 \002(\003\022\020\n\010modified\030\003 \002(\003\022\016\n\006origin\030\004 \002(" +
      "\003\022\016\n\006pushed\030\005 \002(\003\022\014\n\004name\030\006 \002(\t\022\r\n\005value" +
      "\030\007 \002(\t\022\016\n\006device\030\010 \002(\tB.\n\035edge.datamodel" +
      ".protobuf.eventB\nProtoEvent\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_datamodel_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datamodel_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datamodel_Event_descriptor,
        new java.lang.String[] { "Id", "Created", "Modified", "Origin", "Pushed", "Device", "Reading", });
    internal_static_datamodel_Reading_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datamodel_Reading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datamodel_Reading_descriptor,
        new java.lang.String[] { "Id", "Created", "Modified", "Origin", "Pushed", "Name", "Value", "Device", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
